CREATE TABLE IF NOT EXISTS {{table}} (
    id VARCHAR(191) PRIMARY KEY,
    category VARCHAR(255) NOT NULL,
    goal VARCHAR(255) NOT NULL,
    importance VARCHAR(64) NOT NULL,
    status VARCHAR(64) NOT NULL,
    text TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
